# Server
server:
  port: 8082
  servlet:
    context-path: 
  tomcat:
    max-http-post-size: 10291456

logging:
  file: /logs/rabobank/rabobank_inventory.log 
  level:
    org.springframework.web: ERROR
    com.canidateid: INFO
    org.hibernate: ERROR

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  



